### PR TITLE
Add tests to ensure AltoRouter can match against root paths

### PR DESCRIPTION
**Pull request by joelambert**
Waiting on AltoRouter to do a release including https://github.com/dannyvankooten/AltoRouter/pull/247

Issue: https://github.com/dannyvankooten/AltoRouter/issues/258

- [x] Add tests
- [x] Test on updated AltoRouter release
- [x] Increase minimum AltoRouter version in `composer.json`

### CODE REVIEW

**Comment by nlemoine** [comment]
Thanks a lot!

**Comment by nlemoine** [comment]
Hi @joelambert, 

https://github.com/dannyvankooten/AltoRouter/releases/tag/2.0.2

🎉

**Comment by joelambert** [comment]
Thanks @nlemoine, I've updated the minimum version of the package but doesn't look like the tag has made it's way to Packagist yet. Have left a note on the [original Alto issue](https://github.com/dannyvankooten/AltoRouter/issues/258#issuecomment-926509654).

**Comment by joelambert** [comment]
@nlemoine I've merged this and tagged as `v6.0.1` https://github.com/Rareloop/router/releases/tag/v6.0.1 👍

**Comment by nlemoine** [comment]
Thanks 🎉!

**Pull request merged**
